* Emacs channel
** Quickstart

To use this channel, add to your ~.config/guix/channels.scm~:

#+begin_src scheme
(cons*
 (channel
  (name 'emacs)
  (url "https://github.com/babariviere/guix-emacs")
  (introduction
   (make-channel-introduction
    "72ca4ef5b572fea10a4589c37264fa35d4564783"
    (openpgp-fingerprint
     "261C A284 3452 FB01 F6DF  6CF4 F9B7 864F 2AB4 6F18"))))
 ;; other channels here...
 )
#+end_src

Then run ~guix pull~ to be able to install packages.

** Content of this channel
*** Melpa
In ~(emacs packages melpa)~, you have a list of all packages from melpa (unstable).
These will be updated daily.

All packages that are unfetchable will not be included in the package list.
If this happens, you can always use ~guix import elpa -t melpa <package_name+>~.

** What can be improved
*** Handle package download failure
When a package failed to be downloaded, there is no way to handle dependencies that needs this package.

One way to solve this would be to represent the dependency tree to easily remove affected packages (if needed).

*** Allow to add dependencies manually
Some packages depends on "system" packages to be able to build.
The idea would be to specify a package list and their dependencies that will be injected after creating the package literal.
